FROM node:16-alpine as frontend-build

WORKDIR /app


COPY frontend/package.json frontend/yarn.lock ./
RUN yarn install

COPY frontend/ ./

ARG REACT_APP_GRAPHQL_ENDPOINT

RUN yarn build

FROM nginx
COPY --from=frontend-build /app/build /usr/share/nginx/html