FROM node:16-alpine

WORKDIR /app
ENV NODE_ENV production

COPY package.json yarn.lock ./
RUN yarn install --production && yarn cache clean

COPY tsconfig.json ./
COPY prisma/ ./prisma
COPY __generated__ ./__generated__
COPY utils ./utils
RUN yarn generate:db:prod

COPY src/ ./src

CMD yarn prisma migrate deploy && $(yarn bin)/ts-node src/index.ts