version: "3"

volumes:
  chirp-data:

services:
  db:
    image: postgres:14-alpine
    container_name: chirp-db
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - chirp-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tsjierptsjierp
      - POSTGRES_USER=chirp

  server:
    build:
      dockerfile: Dockerfile.backend
      context: .
    container_name: chirp-server
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://chirp:tsjierptsjierp@chirp-db:5432/chirp
    ports:
      - 5000:5000

  web:
    build:
      dockerfile: Dockerfile.frontend
      context: .
      args:
        REACT_APP_GRAPHQL_ENDPOINT: http://localhost:5000/graphql
    container_name: chirp-web
    depends_on:
      - server
    ports:
      - 8080:80
