fragment ChirpListItem on Chirp {
  id
  author {
    id
    name
  }
  createdAt
  updatedAt
  title
  content
}

query ChirpsList {
  chirps(where: { deleted: { equals: false } }, orderBy: { createdAt: desc }) {
    ...ChirpListItem
  }
}
