fragment ChirpBase on Chirp {
  id
  createdAt
  updatedAt
  title
  content
}
fragment ChirpListItem on Chirp {
  ...ChirpBase
  authorId
}

query ChirpsList {
  chirps(where: { deleted: { equals: false } }) {
    ...ChirpListItem
  }
}
